@echo off
setlocal
cd /d %~dp0

set MAX_ITERS=1000
set WARMUP_MS=0
set SLEEP_BETWEEN_ITERS_MS=0
set TARGET_PROMOTED_ONLY=0
set RL_MIN_RETRAIN_INTERVAL_MINUTES=0
set ML_MIN_RETRAIN_INTERVAL_MINUTES=99999
set RL_MAX_CONSECUTIVE_NON_PROMOTED=999999
set RL_DISABLE_PACING=true
set RL_EPISODES=4
set RL_MIN_EPISODES=2
set RL_EARLY_STOP_PATIENCE=2
set ML_RETRAIN_CANDLES_LIMIT=6000
set ML_RETRAIN_FILLS_LIMIT=4000
set ML_SUPERVISED_WF_FOLDS=1
set ML_RL_WF_FOLDS=1

npm run train:target > train-1000-fast.log 2>&1
exit /b %ERRORLEVEL%
